[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "trading-kiwcomp-models"
version = "0.1.18"
description = "Trading data models (Binance, Kafka, Postgres) for KiwComp"
readme = "README.md"
license = { text = "MIT" }
authors = [
  { name = "Kiw Company", email = "kiw.share.resource@gmail.com" }
]

# Support all modern Python versions
requires-python = ">=3.8"

dependencies = [
  "sqlalchemy",
  "psycopg2-binary",
  "pydantic",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["trading_kiwcomp_models*"]
namespaces = false
